# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQnJgv-DwTpaG8TQzlh3pb83gQQ2_DJH
"""

from stegano import lsb

secret = lsb.hide("pilot.png", "hi i am erik maulana this is steganography")
secret.save("pilot.png")

from stegano import lsb

print(lsb.reveal("pilot.png"))

!pip install stegano